import path from "node:path";

// Fixed UUIDs/emails from supabase/seed.sql — stable across `pnpm db:reset`,
// safe to hardcode. Restaurant 1 ("Dineinly Test Kitchen") is the small
// hand-authored fixture; Restaurant 2 ("Arbor Brewing Company") is the large
// 30-table fixture, used strictly read-only (see e2e/README.md).

export const RESTAURANT_1_ID = "10000000-0000-4000-8000-000000000001";
export const RESTAURANT_2_ID = "10000000-0000-4000-8000-000000000002";

// import.meta.dirname, not __dirname — e2e/package.json's "type": "module"
// makes this a real ES module at runtime, no CommonJS globals available.
export const STORAGE_STATE_DIR = path.join(
	import.meta.dirname,
	"..",
	"storageState",
);

export type OtpRoleName =
	| "dineinlyAdmin"
	| "owner"
	| "manager"
	| "waiter"
	| "kitchen";

type OtpRole = {
	email: string;
	storageStatePath: string;
};

// The five identities global-setup.ts authenticates once via the real
// Email-OTP flow. Every spec file that needs one of these sessions does
// `test.use({ storageState: OTP_ROLES.owner.storageStatePath })` instead of
// signing in itself.
export const OTP_ROLES: Record<OtpRoleName, OtpRole> = {
	dineinlyAdmin: {
		email: "admin@dineinly.com",
		storageStatePath: path.join(STORAGE_STATE_DIR, "dineinly-admin.json"),
	},
	owner: {
		email: "owner@dineinly.test",
		storageStatePath: path.join(STORAGE_STATE_DIR, "owner.json"),
	},
	manager: {
		email: "manager@dineinly.test",
		storageStatePath: path.join(STORAGE_STATE_DIR, "manager.json"),
	},
	waiter: {
		email: "waiter@dineinly.test",
		storageStatePath: path.join(STORAGE_STATE_DIR, "waiter.json"),
	},
	kitchen: {
		email: "kitchen@dineinly.test",
		storageStatePath: path.join(STORAGE_STATE_DIR, "kitchen.json"),
	},
};

// Arbor's owner is authenticated ad hoc (its own storageState, generated by
// global-setup alongside the Restaurant 1 roles) — tables.spec.ts is the
// only file that needs it, for the read-only 30-table/merged-group checks.
export const ARBOR_OWNER_EMAIL = "owner@arborbrewing.test";
export const ARBOR_OWNER_STORAGE_STATE = path.join(
	STORAGE_STATE_DIR,
	"arbor-owner.json",
);

// Restaurant 1 — staff row ids (packages/db `staff.id`), for API-level
// assertions that need the row id rather than just the email.
export const RESTAURANT_1_STAFF = {
	owner: { id: "20000000-0000-4000-8000-000000000001", name: "Asha Rao" },
	manager: { id: "20000000-0000-4000-8000-000000000002", name: "Ravi Shetty" },
	waiter: { id: "20000000-0000-4000-8000-000000000003", name: "Priya Nair" },
	kitchen: { id: "20000000-0000-4000-8000-000000000004", name: "Vikram Das" },
	invitedWaiter: {
		id: "20000000-0000-4000-8000-000000000005",
		name: "Meera Iyer",
		email: "waiter2@dineinly.test",
	},
} as const;

// Restaurant 1 tables — T1/T2 occupied (seeded active/closed sessions), T3/T4
// free. Guest-ordering specs use a free table's QR so they never collide
// with the seeded active session's own cart/orders.
export const RESTAURANT_1_TABLES = {
	t1Occupied: { qrToken: "seed-qr-table-1", label: "T1" },
	t2Occupied: { qrToken: "seed-qr-table-2", label: "T2" },
	t3Free: { qrToken: "seed-qr-table-3", label: "T3" },
	t4Free: { qrToken: "seed-qr-table-4", label: "T4" },
} as const;

// Arbor — the fixtures tables.spec.ts's read-only checks assert against.
export const ARBOR_TABLES = {
	communal: { qrToken: "arbor-qr-table-t15", label: "T15" },
	mergedGroup: ["T20", "T21", "T22", "T23"] as const,
	free: { qrToken: "arbor-qr-table-t26", label: "T26" },
} as const;
